export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';
export const CLEAR_SEARCH_TEXT = 'CLEAR_SEARCH_TEXT';
export const SET_PLANET_LIST = 'SET_PLANET_LIST';
export const START_LOAD_PLANET_LIST = 'START_LOAD_PLANET_LIST';
export const STOP_LOAD_PLANET_LIST = 'STOP_LOAD_PLANET_LIST';